cant stand (disabled) (prism disabling reference)
milenakos/cat-bot pull request #136
Opened 2024-11-06 16:51 UTC by NatalieCrazy

uhhhhh if this is absolute garbage im sorry

2024-11-06 17:03 UTC, ZakChrom requested changes

2024-11-06 17:03 UTC, ZakChrom commented on main.py
> +                if prism.name = self.prismname:
==

2024-11-06 17:05 UTC, NatalieCrazy commented on main.py
> +                if prism.name = self.prismname:
its joever

2024-11-07 12:54 UTC, NatalieCrazy commented
ok i think we good now

2024-11-07 12:56 UTC, milenakos approved these changes
istg if this will still crash

2024-11-07 12:56 UTC, MonkeysWithPie commented
good luck

2024-11-07 12:56 UTC, merged